In [2]:
import pandas as pd

df = pd.DataFrame({
    "hours_studied": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "marks": [35, 42, 48, 55, 58, 65, 72, 78, 85, 92, 96, 99]
})

df

    hours_studied  marks
0               1     35
1               2     42
2               3     48
3               4     55
4               5     58
5               6     65
6               7     72
7               8     78
8               9     85
9              10     92
10             11     96
11             12     99

In [5]:
mean_marks=df["marks"].mean()
print(mean_marks)
df["prediction_0"] = mean_marks

df

68.75

    hours_studied  marks  prediction_0
0               1     35         68.75
1               2     42         68.75
2               3     48         68.75
3               4     55         68.75
4               5     58         68.75
5               6     65         68.75
6               7     72         68.75
7               8     78         68.75
8               9     85         68.75
9              10     92         68.75
10             11     96         68.75
11             12     99         68.75

In [6]:
df["residual"]=df["marks"]-df["prediction_0"]
print(df)

    hours_studied  marks  prediction_0  residual
0               1     35         68.75    -33.75
1               2     42         68.75    -26.75
2               3     48         68.75    -20.75
3               4     55         68.75    -13.75
4               5     58         68.75    -10.75
5               6     65         68.75     -3.75
6               7     72         68.75      3.25
7               8     78         68.75      9.25
8               9     85         68.75     16.25
9              10     92         68.75     23.25
10             11     96         68.75     27.25
11             12     99         68.75     30.25