In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score,silhouette_score,precision_score,mean_squared_error

In [33]:
data=pd.read_csv("Test.csv")
df=pd.DataFrame(data)

In [34]:
df.head()

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1
0,458989,Female,Yes,36,Yes,Engineer,0.0,Low,1.0,Cat_6
1,458994,Male,Yes,37,Yes,Healthcare,8.0,Average,4.0,Cat_6
2,458996,Female,Yes,69,No,NaN,0.0,Low,1.0,Cat_6
3,459000,Male,Yes,59,No,Executive,11.0,High,2.0,Cat_6
4,459001,Female,No,19,No,Marketing,NaN,Low,4.0,Cat_6

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2627 entries, 0 to 2626
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               2627 non-null   int64
 1   Gender           2627 non-null   str
 2   Ever_Married     2577 non-null   str
 3   Age              2627 non-null   int64
 4   Graduated        2603 non-null   str
 5   Profession       2589 non-null   str
 6   Work_Experience  2358 non-null   float64
 7   Spending_Score   2627 non-null   str
 8   Family_Size      2514 non-null   float64
 9   Var_1            2595 non-null   str
dtypes: float64(2), int64(2), str(6)
memory usage: 276.0 KB

In [36]:
df.describe()

                  ID          Age  Work_Experience  Family_Size
count    2627.000000  2627.000000      2358.000000  2514.000000
mean   463433.918919    43.649791         2.552587     2.825378
std      2618.245698    16.967015         3.341094     1.551906
min    458989.000000    18.000000         0.000000     1.000000
25%    461162.500000    30.000000         0.000000     2.000000
50%    463379.000000    41.000000         1.000000     2.000000
75%    465696.000000    53.000000         4.000000     4.000000
max    467968.000000    89.000000        14.000000     9.000000

In [37]:
df.isnull().sum()

ID                   0
Gender               0
Ever_Married        50
Age                  0
Graduated           24
Profession          38
Work_Experience    269
Spending_Score       0
Family_Size        113
Var_1               32
dtype: int64

In [38]:
df["Ever_Married"] = df["Ever_Married"].fillna(df["Ever_Married"].mode()[0])
print(df["Ever_Married"].isnull().sum())

0

In [39]:
df["Graduated"]=df["Graduated"].fillna(df["Graduated"].mode()[0])
print("Not fill values of Graduated",df["Graduated"].isnull().sum())

Not fill values of Graduated 0

In [47]:
df["Profession"] = df["Profession"].fillna("Unknown")

print("Not fill values of Profession",df["Profession"].isnull().sum())

Not fill values of Profession 0

In [48]:
df["Work_Experience"] = df["Work_Experience"].fillna(df["Work_Experience"].median())

print("Not fill value of Work_Experience",df["Work_Experience"].isnull().sum())

Not fill value of Work_Experience 0

In [49]:
df.isnull().sum(


)

ID                  0
Gender              0
Ever_Married        0
Age                 0
Graduated           0
Profession          0
Work_Experience     0
Spending_Score      0
Family_Size         0
Var_1              32
dtype: int64

In [50]:
df["Family_Size"]=df['Family_Size'].fillna(df["Family_Size"].median())
print(df["Family_Size"].isnull().sum())

0

In [51]:
df.isnull().sum()

ID                  0
Gender              0
Ever_Married        0
Age                 0
Graduated           0
Profession          0
Work_Experience     0
Spending_Score      0
Family_Size         0
Var_1              32
dtype: int64

In [54]:
df["Var_1"] = df["Var_1"].fillna(df["Var_1"].mode()[0])

df.isnull().sum()

ID                 0
Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
Var_1              0
dtype: int64

In [56]:
# After all your fillna steps...

# Save to a new CSV file
df.to_csv("Cleaned_Test.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [57]:
df.describe()

                  ID          Age  Work_Experience  Family_Size
count    2627.000000  2627.000000      2627.000000  2627.000000
mean   463433.918919    43.649791         2.393605     2.789874
std      2618.245698    16.967015         3.200165     1.527360
min    458989.000000    18.000000         0.000000     1.000000
25%    461162.500000    30.000000         0.000000     2.000000
50%    463379.000000    41.000000         1.000000     2.000000
75%    465696.000000    53.000000         3.000000     4.000000
max    467968.000000    89.000000        14.000000     9.000000

In [58]:
df.head()

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1
0,458989,Female,Yes,36,Yes,Engineer,0.0,Low,1.0,Cat_6
1,458994,Male,Yes,37,Yes,Healthcare,8.0,Average,4.0,Cat_6
2,458996,Female,Yes,69,No,Artist,0.0,Low,1.0,Cat_6
3,459000,Male,Yes,59,No,Executive,11.0,High,2.0,Cat_6
4,459001,Female,No,19,No,Marketing,1.0,Low,4.0,Cat_6

In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import  seaborn as sns
data=pd.read_csv("Cleaned_Test.csv")
df=data.copy()

In [61]:
print("Rows",df.shape[0])
print("columns",df.shape[1])

Rows 2627
columns 10